bonitasoft/bonita-engine

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/process/ProcessManagementIT.java
bonita-integration-tests/bonita-query-tests/src/test/java/org/bonitasoft/engine/core/process/instance/model/ConnectorInstanceQueriesTest.java
bonita-integration-tests/bonita-query-tests/src/test/java/org/bonitasoft/engine/test/persistence/repository/ConnectorInstanceRepository.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/api/ProcessRuntimeAPI.java
bpm/bonita-connector-service/bonita-connector-service-api-impl/src/main/java/org/bonitasoft/engine/core/connector/impl/ConnectorInstanceServiceImpl.java
bpm/bonita-connector-service/bonita-connector-service-api-impl/src/test/java/org/bonitasoft/engine/core/connector/impl/ConnectorInstanceServiceImplTest.java
bpm/bonita-connector-service/bonita-connector-service-api/src/main/java/org/bonitasoft/engine/core/connector/ConnectorInstanceService.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/ProcessAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/connector/ConnectorResetStrategy.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/connector/ConnectorReseter.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/connector/ResetAllFailedConnectorStrategy.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/flownode/FlowNodeRetrier.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/FlowNodeExecutorImpl.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/connector/ConnectorReseterTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/connector/ResetAllFailedConnectorStrategyTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/flownode/FlowNodeRetrierTest.java
bpm/bonita-core/bonita-process-instance/bonita-process-instance-impl/src/main/resources/org/bonitasoft/engine/core/process/instance/model/impl/hibernate/process.instance.queries.hbm.xml

- update javadoc
- re-use logic of retryTask into replayActivity to avoid code duplication.

BS-12685, fix method retryTask by re-executing failing connectors.

---

bpm/bonita-sql/src/main/resources/sql/mysql/postCreateStructure.sql
bpm/bonita-sql/src/main/resources/sql/mysql/preDropStructure.sql

complement to migration PR on same issue

BS-12869, Fix deadlock on MySql migration when resuming tenant

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/activity/UserTaskContractITest.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/bar/xml/ComplexInputDefinitionBinding.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/contract/impl/ComplexInputDefinitionImpl.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/contract/impl/ContractDefinitionImpl.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/contract/impl/InputDefinitionImpl.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/contract/impl/SimpleInputDefinitionImpl.java
bpm/bonita-util/bonita-client-util/src/test/java/org/bonitasoft/engine/bar/BusinessArchiveTest.java

the xml binding was not good on client side

BS-13145, fix xml binding of contract complex input

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/form/FormMappingIT.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/api/ProcessConfigurationAPI.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/ProcessConfigurationAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/ProcessConfigurationAPIImplTest.java
services/bonita-page/bonita-page-api/src/main/java/org/bonitasoft/engine/page/PageMappingService.java
services/bonita-page/bonita-page-impl/src/main/java/org/bonitasoft/engine/page/impl/PageMappingServiceImpl.java
services/bonita-page/bonita-page-impl/src/test/java/org/bonitasoft/engine/page/impl/SPageMappingServiceImplTest.java

Authorization rules should not be checked when trying to display a page resource

BS-13238 - Authorization rules should not be checked when trying to

---

bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/page/AuthorizationRuleWithParameters.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/page/IsInvolvedInProcessInstanceRule.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/page/IsProcessInitiatorRule.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/page/IsTaskPerformerRule.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/page/IsInvolvedInProcessInstanceRuleTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/page/IsProcessInitiatorRuleTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/page/IsTaskPerformerRuleTest.java
bpm/bonita-home/src/main/resources/bonita-tenant-community.xml

BS-13240 - Authorization rules should not retrieve the user ID in the query string

BS-13240 - Authorization rules should not retrieve the user ID in the

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/activity/UserTaskContractITest.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/process/impl/ContractDefinitionBuilder.java
bpm/bonita-api/bonita-common-api-impl/src/test/java/org/bonitasoft/engine/bpm/process/impl/ContractDefinitionBuilderTest.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/bpm/contract/validation/ContractStructureValidator.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/contract/validation/ContractConstraintsValidatorTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/contract/validation/ContractStructureValidatorTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/contract/validation/builder/MapBuilder.java
bpm/bonita-util/bonita-client-util/src/test/java/org/bonitasoft/engine/bar/BusinessArchiveTest.java

I was not able to run IT.
Can someone checkout the branch and run tests ?

remove mandatory constraint from builder

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/page/PageAPIIT.java
bonita-integration-tests/bonita-test-utils/bonita-common-test-utils/src/main/java/org/bonitasoft/engine/test/CommonTestUtil.java
bpm/bonita-core/bonita-home-server/src/test/java/org/bonitasoft/engine/DeepRegexFileFilterTest.java
bpm/bonita-home/src/main/resources/bonita-tenant-community.xml
services/bonita-page/bonita-page-impl/src/main/java/org/bonitasoft/engine/page/PageServiceListener.java
services/bonita-page/bonita-page-impl/src/main/java/org/bonitasoft/engine/page/impl/ApiExtensionPageServiceListenerImpl.java
services/bonita-page/bonita-page-impl/src/main/java/org/bonitasoft/engine/page/impl/PageServiceImpl.java
services/bonita-page/bonita-page-impl/src/main/java/org/bonitasoft/engine/page/impl/SPageContentHelper.java
services/bonita-page/bonita-page-impl/src/test/java/org/bonitasoft/engine/page/impl/ApiExtensionPageServiceListenerImplTest.java
services/bonita-page/bonita-page-impl/src/test/java/org/bonitasoft/engine/page/impl/PageServiceImplTest.java

First step before support of multiple extensions in a zip

BS-13276, use property file to define multiple resources

---

bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/bar/xml/DocumentDefinitionBinding.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/bar/xml/XMLProcessDefinition.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/document/impl/DocumentDefinitionImpl.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/process/impl/DocumentDefinitionBuilder.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/process/impl/ProcessDefinitionBuilder.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/bpm/document/DocumentDefinition.java
bpm/bonita-api/bonita-common-api/src/main/resources/org/bonitasoft/engine/bpm/bar/ProcessDefinition.xsd
bpm/bonita-core/bonita-process-definition/bonita-process-definition-api/src/main/java/org/bonitasoft/engine/core/process/definition/model/SDocumentDefinition.java
bpm/bonita-core/bonita-process-definition/bonita-process-definition-impl/src/main/java/org/bonitasoft/engine/core/process/definition/model/bindings/SDocumentDefinitionBinding.java
bpm/bonita-core/bonita-process-definition/bonita-process-definition-impl/src/main/java/org/bonitasoft/engine/core/process/definition/model/bindings/XMLSProcessDefinition.java
bpm/bonita-core/bonita-process-definition/bonita-process-definition-impl/src/main/java/org/bonitasoft/engine/core/process/definition/model/impl/SDocumentDefinitionImpl.java
bpm/bonita-core/bonita-process-definition/bonita-process-definition-impl/src/main/resources/org/bonitasoft/engine/core/process/definition/model/builder/impl/SProcessDefinition.xsd
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/ProcessExecutorImpl.java
bpm/bonita-util/bonita-client-util/src/test/java/org/bonitasoft/engine/bar/BusinessArchiveTest.java

Only did the model server + client
will implement it after

BS-13321, add initial value expression on document definition model

---

services/bonita-page/bonita-page-impl/src/main/java/org/bonitasoft/engine/page/PageServiceListener.java
services/bonita-page/bonita-page-impl/src/main/java/org/bonitasoft/engine/page/impl/ApiExtensionPageServiceListenerImpl.java
services/bonita-page/bonita-page-impl/src/main/java/org/bonitasoft/engine/page/impl/PageServiceImpl.java
services/bonita-page/bonita-page-impl/src/test/java/org/bonitasoft/engine/page/impl/ApiExtensionPageServiceListenerImplTest.java
services/bonita-page/bonita-page-impl/src/test/java/org/bonitasoft/engine/page/impl/PageServiceImplTest.java

BS-13140, when updating a page content, api extension listener updates

---

bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/PlatformAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/profile/ProfileImportStrategy.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/profile/ProfilesImporter.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/profile/ProfilesUpdaterRestartHandler.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/profile/ProfilesUpdaterRestartHandlerTest.java
services/bonita-profile/bonita-profile-api/src/main/java/org/bonitasoft/engine/profile/ProfileService.java
services/bonita-profile/bonita-profile-impl/src/main/java/org/bonitasoft/engine/profile/impl/ProfileServiceImpl.java

Regrouped all code dealing with default profiles creation and update into ProfilesUpdaterRestartHandler (removed some that was in PlatformAPIImpl).

Default profiles are now created and updated by ProfilesUpdaterRestartHandler

---

bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/bpm/contract/validation/ContractStructureValidator.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/bpm/contract/validation/ContractTypeValidator.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/bpm/contract/validation/ContractValidator.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/contract/validation/ContractConstraintsValidatorTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/contract/validation/ContractStructureValidatorTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/contract/validation/ContractValidatorTest.java

* Complex sub-elements are not checked if complex value is null
* Complex type validation is not performed if complex value is null

BS-13498, not null inputs are allowed:

---

bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/PlatformAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/transaction/platform/ActivateTenant.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/PlatformAPIImplTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/transaction/platform/ActivateTenantTest.java
services/bonita-scheduler/bonita-scheduler-api/src/main/java/org/bonitasoft/engine/scheduler/SchedulerService.java

Reverts bonitasoft/bonita-engine#92

Revert "Default jobs are now updated at tenant start"

---

bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/PlatformAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/PlatformAPIImplTest.java

There is now a check in start node to ensure that default jobs are deployed.
This check applies to initial startup (platform creation) and node restarts.
As a bonus, I have also improved unit tests for the PlatformAPI but there is still plenty of room for improvement.

Default jobs are now created and updated at tenant start

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/business/data/BDRepositoryIT.java
bonita-integration-tests/bonita-integration-tests-client/src/main/resources/org/bonitasoft/engine/business/data/getBusinessDataByIdsEmployee.json
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/command/GetBusinessDataByIdsCommand.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/command/GetBusinessDataByIdsCommandTest.java
bpm/bonita-home/src/main/resources/bonita-tenant-community.xml
services/bonita-business-data/bonita-business-data-api/src/main/java/org/bonitasoft/engine/business/data/BusinessDataRepository.java
services/bonita-business-data/bonita-business-data-api/src/main/java/org/bonitasoft/engine/business/data/BusinessDataService.java
services/bonita-business-data/bonita-business-data-api/src/main/java/org/bonitasoft/engine/business/data/JsonBusinessDataSerializer.java
services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/BusinessDataServiceImpl.java
services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/JPABusinessDataRepositoryImpl.java
services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/JsonBusinessDataSerializerImpl.java
services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/BusinessDataServiceImplTest.java

BS-12692, add command which gets business objects according to its

---

bpm/bonita-core/bonita-login/bonita-login-api-impl/pom.xml
bpm/bonita-core/bonita-login/bonita-login-api-impl/src/main/java/org/bonitasoft/engine/core/login/SecuredLoginServiceImpl.java
bpm/bonita-core/bonita-login/bonita-login-api-impl/src/test/java/org/bonitasoft/engine/core/login/SecuredLoginServiceImplTest.java
bpm/bonita-core/bonita-login/bonita-login-api/src/main/java/org/bonitasoft/engine/core/login/LoginService.java
bpm/bonita-home/src/main/resources/bonita-tenant-community.xml

BS-13486 - add technical logs in Login service + remove deprecated methods

BS-13486 - add technical logs in Login service

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/form/FormMappingIT.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/resolver/FormMappingAndPageDependencyDeployer.java

form mapping where ignored for event sub process

BS-13693, fix form mapping for event sub process

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/identity/UserIT.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/identity/UserSearchDescriptor.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/search/descriptor/SearchUserDescriptor.java

Add ID in UserSearchDescriptor

BS-13772 - Unable to list users with their ID in data table due to API limitation

---

bpm/bonita-util/bonita-common-util/src/main/java/org/bonitasoft/engine/bdm/BDMQueryUtil.java
bpm/bonita-util/bonita-common-util/src/test/java/org/bonitasoft/engine/bdm/BDMQueryUtilTest.java
services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/bdm/client/ClientBDMCodeGeneratorTest.java
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/AddressDAOImplWithLazyReferenceOnEmployee.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/AddressDAOWithLazyReferenceOnEmployee.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/Employee.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeListAggregation.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeListComposition.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeSimpleAggregation.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeSimpleComposition.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/ForecastList.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/PersonneDAOImpl.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/Skill.java.txt

Add findByPersistenceId provided query.
Do not add the query if already defined in custom queries (avoids
migration issues)

BS-13861 Add findByPersistenceId provided query

---

services/bonita-business-data/bonita-business-data-api/src/main/java/org/bonitasoft/engine/business/data/proxy/ServerProxyfier.java
services/bonita-business-data/bonita-business-data-api/src/test/java/org/bonitasoft/engine/business/data/proxy/ServerProxyfierTest.java

Handle null entity in server proxifier

BS-13800 Fix npe in ServerProxyfier

---

bpm/bonita-home/build-home.xml
bpm/bonita-home/src/main/resources/README.md

It mainly describes the structure
We are lacking documentation on the bonita home structure that's why I added this README

Added a new README.md file inside the bonita home

---

services/bonita-persistence/bonita-persistence-hibernate/src/main/java/org/bonitasoft/engine/persistence/AbstractHibernatePersistenceService.java
services/bonita-persistence/bonita-persistence-hibernate/src/main/java/org/bonitasoft/engine/persistence/TenantHibernatePersistenceService.java
services/bonita-persistence/bonita-persistence-read/src/main/java/org/bonitasoft/engine/persistence/SRetryableException.java
services/bonita-transaction/bonita-transaction-api/src/main/java/org/bonitasoft/engine/transaction/TransactionService.java
services/bonita-transaction/bonita-transaction-impl/src/main/java/org/bonitasoft/engine/transaction/JTATransactionServiceImpl.java
services/bonita-transaction/bonita-transaction-impl/src/main/java/org/bonitasoft/engine/transaction/JTATransactionWrapper.java
services/bonita-transaction/bonita-transaction-impl/src/test/java/org/bonitasoft/engine/transaction/JTATransactionServiceImplTest.java

some cleanup:
- remove dead code
- group exceptions
- ...

BS-13411, clean up code on JTATransactionService

---

bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/api/DocumentAPI.java

update the javadoc to explain that the method work only on open cases

BS-14031 update javadoc of getLastDocument

---

bpm/bonita-core/bonita-process-instance/bonita-process-instance-impl/src/main/java/org/bonitasoft/engine/core/process/instance/impl/GatewayInstanceServiceImpl.java
bpm/bonita-core/bonita-process-instance/bonita-process-instance-impl/src/test/java/org/bonitasoft/engine/core/process/instance/impl/GatewayInstanceServiceImplTest.java

There was no reach state date and last update date on gateway instance object and archived gateway instance object

BS-13438, add timestamp on gateway instance

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/process/document/DocumentIT.java
bpm/bonita-core/bonita-document/bonita-document-impl/src/main/java/org/bonitasoft/engine/core/document/api/impl/DocumentServiceImpl.java
bpm/bonita-core/bonita-document/bonita-document-impl/src/main/java/org/bonitasoft/engine/core/document/model/recorder/SelectDescriptorBuilder.java
bpm/bonita-core/bonita-document/bonita-document-impl/src/main/resources/org/bonitasoft/engine/core/document/model/impl/hibernate/archive.document.queries.hbm.xml
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/search/descriptor/SearchArchivedDocumentDescriptor.java

make getArchiveProcessDocument return the last version when a document changed more than one time
Just added an order by archive date DESC in the query

BS-13476, make getArchiveProcessDoc return last version

---

bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/api/impl/ClientInterceptor.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/ServerAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/service/impl/ServiceAccessorFactory.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/ServerAPIImplTest.java
services/bonita-commons/src/main/java/org/bonitasoft/engine/commons/ClassReflector.java

call warning when checking the method accessibility + some code cleanup

BS-1698, log warning when calling deprecated API method

---

bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/FlowNodeStateManagerImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/archive/ProcessArchiver.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/handler/ArchiveProcessInstancesHandler.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/state/AbortingCallActivityStateImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/state/CancellingCallActivityStateImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/state/CompletingCallActivityStateImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/state/EndingCallActivityExceptionStateImpl.java
bpm/bonita-home/src/main/resources/bonita-tenant-community.xml
services/bonita-data-instance/bonita-data-instance-api/src/main/java/org/bonitasoft/engine/data/instance/api/DataInstanceService.java
services/bonita-data-instance/bonita-data-instance-impl/pom.xml
services/bonita-data-instance/bonita-data-instance-impl/src/main/java/org/bonitasoft/engine/data/instance/api/impl/DataInstanceServiceImpl.java
services/bonita-data-instance/bonita-data-instance-impl/src/test/java/org/bonitasoft/engine/data/instance/api/impl/DataInstanceServiceImplTest.java

Data were archived on process archiving but it was not usefull because data are archived already after each update and on creation

BS-13731, remove the last archiving of data

---

bonita-integration-tests/bonita-integration-tests-local/src/main/java/org/bonitasoft/engine/test/PermissionAPIIT.java
bonita-integration-tests/bonita-test-utils/bonita-server-test-utils/src/main/java/org/bonitasoft/engine/test/util/PlatformUtil.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/home/BonitaHome.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/io/IOUtil.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/io/PropertiesManager.java
bpm/bonita-connector-service/bonita-connector-service-api-impl/src/main/java/org/bonitasoft/engine/core/connector/impl/ConnectorServiceImpl.java
bpm/bonita-connector-service/bonita-connector-service-api-impl/src/test/java/org/bonitasoft/engine/core/connector/impl/ConnectorServiceImplTest.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/BonitaHomeServer.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/BonitaResource.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/Folder.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/ProcessManager.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/TenantManager.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/TenantStorage.java
bpm/bonita-core/bonita-home-server/src/test/java/org/bonitasoft/engine/home/BonitaHomeServerTest.java
bpm/bonita-core/bonita-home-server/src/test/java/org/bonitasoft/engine/home/ProcessManagerTest.java
bpm/bonita-core/bonita-parameter/bonita-parameter-propertyfile/src/main/java/org/bonitasoft/engine/parameter/propertyfile/PropertyFileParameterService.java
bpm/bonita-core/bonita-parameter/bonita-parameter-propertyfile/src/test/java/org/bonitasoft/engine/parameter/propertyfile/PropertyFileParameterServiceTest.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/PlatformAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/ProcessAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/ProcessManagementAPIImplDelegate.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/resolver/DependencyResolver.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/ProcessExecutorImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/profile/ProfilesImporter.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/service/impl/PermissionServiceImpl.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/service/impl/PermissionServiceImplTest.java
bpm/bonita-core/bonita-user-filter/bonita-user-filter-impl/src/main/java/org/bonitasoft/engine/core/filter/impl/UserFilterServiceImpl.java
services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/BusinessDataModelRepositoryImpl.java
services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/BusinessDataModelRepositoryImplTest.java
services/bonita-incident/bonita-incident-log/src/main/java/org/bonitasoft/engine/incident/FileLoggerIncidentHandler.java
services/bonita-incident/bonita-incident-log/src/test/java/org/bonitasoft/engine/incident/FileLoggerIncidentHandlerTest.java

Reduce the size of BonitaHomeServer class by delegating method to 3 classes
* *ProcessManager*  handles files related to a process
* *TenantManager* create/delete tenant
* *TenantStorage* store files at tenant level
need to be merged with the sp version + __after 7.1__ release

Bonita home server enhance

---

bonita-integration-tests/bonita-integration-tests-local/src/main/java/org/bonitasoft/engine/test/PermissionAPIIT.java
bonita-integration-tests/bonita-test-utils/bonita-server-test-utils/src/main/java/org/bonitasoft/engine/test/util/PlatformUtil.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/home/BonitaHome.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/io/IOUtil.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/io/PropertiesManager.java
bpm/bonita-connector-service/bonita-connector-service-api-impl/src/main/java/org/bonitasoft/engine/core/connector/impl/ConnectorServiceImpl.java
bpm/bonita-connector-service/bonita-connector-service-api-impl/src/test/java/org/bonitasoft/engine/core/connector/impl/ConnectorServiceImplTest.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/BonitaHomeServer.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/BonitaResource.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/Folder.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/ProcessManager.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/TenantManager.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/TenantStorage.java
bpm/bonita-core/bonita-home-server/src/test/java/org/bonitasoft/engine/home/BonitaHomeServerTest.java
bpm/bonita-core/bonita-home-server/src/test/java/org/bonitasoft/engine/home/ProcessManagerTest.java
bpm/bonita-core/bonita-parameter/bonita-parameter-propertyfile/src/main/java/org/bonitasoft/engine/parameter/propertyfile/PropertyFileParameterService.java
bpm/bonita-core/bonita-parameter/bonita-parameter-propertyfile/src/test/java/org/bonitasoft/engine/parameter/propertyfile/PropertyFileParameterServiceTest.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/PlatformAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/ProcessAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/ProcessManagementAPIImplDelegate.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/resolver/DependencyResolver.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/ProcessExecutorImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/profile/ProfilesImporter.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/service/impl/PermissionServiceImpl.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/service/impl/PermissionServiceImplTest.java
bpm/bonita-core/bonita-user-filter/bonita-user-filter-impl/src/main/java/org/bonitasoft/engine/core/filter/impl/UserFilterServiceImpl.java
services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/BusinessDataModelRepositoryImpl.java
services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/BusinessDataModelRepositoryImplTest.java
services/bonita-incident/bonita-incident-log/src/main/java/org/bonitasoft/engine/incident/FileLoggerIncidentHandler.java
services/bonita-incident/bonita-incident-log/src/test/java/org/bonitasoft/engine/incident/FileLoggerIncidentHandlerTest.java

Redo the pull request of bonita home server enhance with the fix on remote tests
The issue of connector not found was due to a bad generation of jars in tests

Split bonita home server in sub classes

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/business/data/BDRepositoryIT.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/business/data/BusinessDataRetriever.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/business/data/BusinessDataRetrieverTest.java
bpm/bonita-home/src/main/resources/bonita-tenant-community.xml
services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/BusinessDataReloader.java
services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/BusinessDataServiceImpl.java
services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/BusinessDataReloaderTest.java
services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/BusinessDataServiceImplTest.java

When the business object is loaded using a Business Object Query, the object is proxyfied and the proxy class was used to load the object from the database.
BS-13090, has fixed the same but in the context of an aggregation.

BS-14362, ensure that the real class is used to load a business object

---

bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/ThemeAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/ThemeAPIImplTest.java
services/bonita-theme/bonita-theme-api/src/main/java/org/bonitasoft/engine/theme/ThemeService.java
services/bonita-theme/bonita-theme-impl/src/main/java/org/bonitasoft/engine/theme/impl/ThemeServiceImpl.java
services/bonita-theme/bonita-theme-impl/src/main/java/org/bonitasoft/engine/theme/persistence/SelectDescriptorBuilder.java
services/bonita-theme/bonita-theme-impl/src/main/resources/org/bonitasoft/engine/theme/model/impl/hibernate/theme.queries.hbm.xml

add specific query for get last update date on theme

---

bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/flownode/impl/internal/ActivityInstanceImpl.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/flownode/impl/internal/ArchivedActivityInstanceImpl.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/flownode/impl/internal/ArchivedFlowNodeInstanceImpl.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/flownode/impl/internal/FlowNodeInstanceImpl.java
bpm/bonita-api/bonita-common-api-impl/src/main/java/org/bonitasoft/engine/bpm/flownode/impl/internal/GatewayInstanceImpl.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/bpm/flownode/ActivityInstance.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/bpm/flownode/ArchivedActivityInstance.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/bpm/flownode/ArchivedFlowNodeInstance.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/bpm/flownode/FlowNodeInstance.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/service/ModelConvertor.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/service/ModelConvertorTest.java

Convertion of journal to archive model was not done
JIRA BS-13438

fix the reachedStateDate not filled when archiving flownode + Server to Client model convertion

---

bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/api/PageAPI.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/page/PageNotFoundException.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/PageAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/page/PageAPIDelegate.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/PageAPIImplTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/page/PageAPIDelegateTest.java

We need this method to avoid creating a mapping with a key that already
exists.

BS-14567 Add method in PageAPI to retrieve a Page from a mapping key

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/page/PageAPIIT.java
bonita-integration-tests/bonita-integration-tests-local/src/test/java/org/bonitasoft/engine/page/PageMappingServiceIT.java
bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/api/PageAPI.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/PageAPIImpl.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/page/PageAPIDelegate.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/PageAPIImplTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/page/PageAPIDelegateTest.java
services/bonita-page/bonita-page-impl/src/main/java/org/bonitasoft/engine/page/impl/PageMappingServiceImpl.java
services/bonita-page/bonita-page-impl/src/main/java/org/bonitasoft/engine/page/impl/PageServiceImpl.java
services/bonita-page/bonita-page-impl/src/test/java/org/bonitasoft/engine/page/impl/PageMappingServiceImplTest.java
services/bonita-page/bonita-page-impl/src/test/java/org/bonitasoft/engine/page/impl/PageServiceImplTest.java

* Do not constraint Index.groovy for rest api extensions
* Check mapping existence before creating it

BS-14620 Allow other restApiController filename for Rest API extension

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/command/ExecuteBDMQueryCommandIT.java
bonita-integration-tests/bonita-integration-tests-client/src/main/resources/org/bonitasoft/engine/command/Employee.find.2.1.json

The ids may change depending on the execution order.

Ignore persistenceId on tests

---

bonita-integration-tests/bonita-integration-tests-local/src/test/java/org/bonitasoft/engine/classloader/ClassLoaderServiceTest.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/bpm/classloader/BonitaBPMParentClassLoaderResolver.java
services/bonita-classloader/bonita-classloader-api/src/main/java/org/bonitasoft/engine/classloader/ClassLoaderIdentifier.java
services/bonita-classloader/bonita-classloader-impl/src/main/java/org/bonitasoft/engine/classloader/ClassLoaderServiceImpl.java
services/bonita-classloader/bonita-classloader-impl/src/main/java/org/bonitasoft/engine/classloader/DefaultParentClassLoaderResolver.java
services/bonita-classloader/bonita-classloader-impl/src/main/java/org/bonitasoft/engine/classloader/VirtualClassLoader.java
services/bonita-classloader/bonita-classloader-impl/src/test/java/org/bonitasoft/engine/classloader/ClassLoaderServiceImplTest.java
services/bonita-classloader/bonita-classloader-impl/src/test/java/org/bonitasoft/engine/classloader/VirtualClassLoaderTest.java

* set scope of virtual classloader at package to avoid creation outside
* have a global classloader identifier instead of null
* add more test to cover notification mechanism

apply review of classloader listener mechanism

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/command/ExecuteBDMQueryCommandIT.java
bpm/bonita-util/bonita-common-util/src/main/java/org/bonitasoft/engine/bdm/BDMQueryUtil.java
bpm/bonita-util/bonita-common-util/src/main/java/org/bonitasoft/engine/bdm/CountQueryGenerator.java
bpm/bonita-util/bonita-common-util/src/main/java/org/bonitasoft/engine/bdm/QueryGenerator.java
bpm/bonita-util/bonita-common-util/src/test/java/org/bonitasoft/engine/bdm/BDMQueryUtilTest.java
bpm/bonita-util/bonita-common-util/src/test/java/org/bonitasoft/engine/bdm/CountQueryGeneratorTest.java
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/AddressDAOImplWithLazyReferenceOnEmployee.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/AddressDAOWithLazyReferenceOnEmployee.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/Employee.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeListAggregation.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeListComposition.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeSimpleAggregation.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeSimpleComposition.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/ForecastList.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/PersonneDAOImpl.java.txt
services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/Skill.java.txt

For a query named "myQuery" the name of related count query is "countForMyQuery"

BS-14530, rename count queries

---

services/bonita-classloader/bonita-classloader-impl/src/main/java/org/bonitasoft/engine/classloader/ClassLoaderServiceImpl.java
services/bonita-classloader/bonita-classloader-impl/src/main/java/org/bonitasoft/engine/classloader/listeners/JacksonCacheClearer.java

clear jackson cache using classloader listeneners

clear jackson cache using classloader listeneners

---

bpm/bonita-util/bonita-common-util/pom.xml
bpm/bonita-util/bonita-common-util/src/main/java/org/bonitasoft/engine/bdm/BusinessObjectModelConverter.java
bpm/bonita-util/bonita-common-util/src/main/java/org/bonitasoft/engine/bdm/model/BusinessObjectModel.java
bpm/bonita-util/bonita-common-util/src/main/resources/info.properties
bpm/bonita-util/bonita-common-util/src/test/java/org/bonitasoft/engine/bdm/BusinessObjectModelConverterTest.java
bpm/bonita-util/bonita-common-util/src/test/java/org/bonitasoft/engine/bdm/model/assertion/Marshaller.java
bpm/bonita-util/bonita-common-util/src/test/resources/bom_7.2.0.xml

* If no version set (new bom or bom < 7.2), then version is set at
marshall time.

BS-14824 Add a modelVersion and a productVersion to the bom.xml

---

bpm/bonita-api/bonita-common-api/src/main/java/org/bonitasoft/engine/api/DocumentAPI.java

fix javadoc for methods getArchivedVersionOfProcessDocument and getArchivedProcessDocument

BS-13942 - fix javadoc

---

bpm/bonita-sql/src/main/resources/sql/h2/createTables.sql
bpm/bonita-sql/src/main/resources/sql/mysql/createTables.sql
bpm/bonita-sql/src/main/resources/sql/oracle/createTables.sql
bpm/bonita-sql/src/main/resources/sql/postgres/createTables.sql
bpm/bonita-sql/src/main/resources/sql/sqlserver/createTables.sql

see also https://github.com/bonitasoft/bonita-migration-sp/pull/31

BS-14442, increase contentName field size to 280 chars

---

bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/bpm/contract/validation/ContractConstraintsValidator.java
bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/bpm/contract/validation/ContractTypeValidator.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/contract/validation/ContractTypeValidatorTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/contract/validation/ContractValidatorTest.java
bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/contract/validation/builder/SComplexInputDefinitionBuilder.java

Merge to branch **release-7.2.0** to be confirmed...

Fix/BS-14869 NPE on multipe complex contract validation

---

pom.xml
services/bonita-commons/pom.xml

see https://issues.apache.org/jira/browse/COLLECTIONS-580

BS-14904 - Upgrade commons-collections version to 3.2.2

---

bonita-test-api/src/main/java/org/bonitasoft/engine/test/TestEngine.java
bonita-test-api/src/main/java/org/bonitasoft/engine/test/TestEngineImpl.java
bonita-test-api/src/main/java/org/bonitasoft/engine/test/internal/EngineStarter.java
bonita-test-api/src/main/java/org/bonitasoft/engine/test/junit/BonitaEngineRule.java
bonita-test-api/src/test/java/org/bonitasoft/engine/test/junit/BonitaEngineRuleTest.java

keepPlatformOnShutdown make the EngineStarter not drop the platform on
shutdown, this is mandatory in order to use this in the mnigration tool

add keepPlatformOnShutdown option on test api

---

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/business/data/BDRepositoryIT.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/FolderMgr.java
bpm/bonita-core/bonita-home-server/src/main/java/org/bonitasoft/engine/home/TenantStorage.java
bpm/bonita-home/src/main/resources/bonita-tenant-community.xml
services/bonita-business-data/bonita-business-data-impl/pom.xml
services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/BusinessDataModelRepositoryImpl.java
services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/BusinessDataModelRepositoryImplTest.java
services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/ConcurrencyIT.java
services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/JPABusinessDataRepositoryImplITest.java

depends on https://github.com/bonitasoft/bonita-engine/pull/259
Store it in database using the TenantResourcesService instead of having
it in the FS in the bonita home

BS-14942 store client-bdm.zip in the TenantResourcesService
