bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/page/PageAPIIT.java
PageIT.should_update_content_return_the_modified_content test on Windows
=> Use UTF-8 encoding when creating new String, it fixes

bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/PlatformAPIImpl.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/transaction/platform/ActivateTenant.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/PlatformAPIImplTest.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/transaction/platform/ActivateTenantTest.java, services/bonita-scheduler/bonita-scheduler-api/src/main/java/org/bonitasoft/engine/scheduler/SchedulerService.java
There is now a check in start node to ensure that default jobs are deployed.
This check applies to initial startup (platform creation) and node restarts.
=> Default jobs are now updated at tenant start

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/process/GatewayExecutionIT.java, bpm/bonita-core/bonita-process-instance/bonita-process-instance-api/src/main/java/org/bonitasoft/engine/core/process/instance/model/SGatewayInstance.java, bpm/bonita-core/bonita-process-instance/bonita-process-instance-impl/src/main/java/org/bonitasoft/engine/core/process/instance/impl/GatewayInstanceServiceImpl.java, bpm/bonita-core/bonita-process-instance/bonita-process-instance-impl/src/main/java/org/bonitasoft/engine/core/process/instance/model/impl/SGatewayInstanceImpl.java, bpm/bonita-core/bonita-process-instance/bonita-process-instance-impl/src/test/java/org/bonitasoft/engine/core/process/instance/impl/GatewayInstanceServiceImplTest.java, bpm/bonita-core/bonita-process-instance/bonita-process-instance-impl/src/test/java/org/bonitasoft/engine/core/process/instance/model/impl/SGatewayInstanceImplTest.java
Root cause: completed gateways (hitbys starting with 'FINISH:') were considered as active.
Fix: handle 'FINISH:' when checking whether a gateway is active
=> BS-13596/inclusive_gateway

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/business/data/BDRepositoryIT.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/ProcessExecutorImpl.java
The context to initialize business data was bad on call activity.
initialize business data was called with the expression context of the call activity but it should have been called using the context of the created sub process
=> BS-13803, fix context used to init business data

bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/transaction/platform/ActivateTenant.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/transaction/platform/DeactivateTenant.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/transaction/platform/ActivateTenantTest.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/transaction/platform/DeactivateTenantTest.java
The bug was happening when we:
- deactivate a tenant that contains processes with start timer
- shuting down the node
- restarting the node
the timer were triggered even if the tenant was deactivated
in 7.0.0 the bug was less visible because work service was shutdown and not restarted with the node
however we had failed jobs
-> now the deactive/activate tenant pause and resume jobs
=> BS-13443, deactivate tenant should pause jobs

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/tenant/TenantMaintenanceIT.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/TenantAdministrationAPIImplTest.java
The previous version of test was using a cycle timer start process to verify if a tenant was correctly paused.
The behaviour of pausing jobs of a given tenant are handled by Quartz and are already tested by Unit Tests, so it's not necessary to test it in an integration test.
After changes we only check that it's not possible to log in a paused tenant and after resuming it, we are able to log in and start a process.
=> BS-11905, rewrite tests to avoid random failure

bpm/bonita-sql/src/main/resources/sql/h2/cleanTables.sql, bpm/bonita-sql/src/main/resources/sql/h2/createTables.sql, bpm/bonita-sql/src/main/resources/sql/h2/deleteTenantObjects.sql, bpm/bonita-sql/src/main/resources/sql/h2/dropTables.sql, bpm/bonita-sql/src/main/resources/sql/h2/postCreateStructure.sql, bpm/bonita-sql/src/main/resources/sql/h2/preDropStructure.sql, bpm/bonita-sql/src/main/resources/sql/mysql/cleanTables.sql, bpm/bonita-sql/src/main/resources/sql/mysql/createTables.sql, bpm/bonita-sql/src/main/resources/sql/mysql/deleteTenantObjects.sql, bpm/bonita-sql/src/main/resources/sql/mysql/dropTables.sql, bpm/bonita-sql/src/main/resources/sql/mysql/postCreateStructure.sql, bpm/bonita-sql/src/main/resources/sql/mysql/preDropStructure.sql, bpm/bonita-sql/src/main/resources/sql/oracle/cleanTables.sql, bpm/bonita-sql/src/main/resources/sql/oracle/createTables.sql, bpm/bonita-sql/src/main/resources/sql/oracle/deleteTenantObjects.sql, bpm/bonita-sql/src/main/resources/sql/oracle/dropTables.sql, bpm/bonita-sql/src/main/resources/sql/oracle/postCreateStructure.sql, bpm/bonita-sql/src/main/resources/sql/oracle/preDropStructure.sql, bpm/bonita-sql/src/main/resources/sql/postgres/cleanTables.sql, bpm/bonita-sql/src/main/resources/sql/postgres/createTables.sql, bpm/bonita-sql/src/main/resources/sql/postgres/deleteTenantObjects.sql, bpm/bonita-sql/src/main/resources/sql/postgres/dropTables.sql, bpm/bonita-sql/src/main/resources/sql/postgres/postCreateStructure.sql, bpm/bonita-sql/src/main/resources/sql/postgres/preDropStructure.sql, bpm/bonita-sql/src/main/resources/sql/sqlserver/cleanTables.sql, bpm/bonita-sql/src/main/resources/sql/sqlserver/createTables.sql, bpm/bonita-sql/src/main/resources/sql/sqlserver/deleteTenantObjects.sql, bpm/bonita-sql/src/main/resources/sql/sqlserver/dropTables.sql, bpm/bonita-sql/src/main/resources/sql/sqlserver/postCreateStructure.sql, bpm/bonita-sql/src/main/resources/sql/sqlserver/preDropStructure.sql
This table was supposed to be removed from scripts in version 7.0.0, but it was missed.
Note: the migration tool will need to also delete this table for installations 7.0.x and 7.1.0
=> BS-13885, remove unused table  arch_transition_instance

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/activity/ContractIT.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/bpm/model/impl/BPMInstancesCreator.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/ProcessExecutor.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/ProcessExecutorImpl.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/StateBehaviors.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/execution/event/EventsHandler.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/expression/ContractInputExpressionExecutorStrategy.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/model/impl/BPMInstancesCreatorTest.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/execution/StateBehaviorsTest.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/expression/ContractInputExpressionExecutorStrategyTest.java
The initialization of process instance with contract input was not good due to wrong Expression context used
Regression was introduces by the fix on Business Data initialization
Cleaned up the start of process to always have the good expression context: in case of call activity use expression context of call activity only for operation execution
=> BS-14270, fix document init with contract input

bonita-integration-tests/bonita-integration-tests-local/src/test/java/org/bonitasoft/engine/continuation/WorkServiceTest.java
Mark shared list used in test as synchronized. Before using a synchronized list I was able to reproduce the issue by executing the test many times (iterate 5000 times),
with synchronized list I was unable to reproduce the issue even iterating 10000 times.
=> BS-9986, try to fix unstable  WorkServiceTest

services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/bdm/EqualsBuilder.java, services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/bdm/HashCodeBuilder.java, services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/bdm/JExprHelper.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/bdm/CodeGeneratorTest.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/bdm/EqualsBuilderTest.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/bdm/HashCodeBuilderTest.java, services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/Entity_equals.java.txt, services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/Entity_hashCode.java.txt, services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/Employee.java.txt, services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeListAggregation.java.txt, services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeListComposition.java.txt, services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeSimpleAggregation.java.txt, services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/EmployeeSimpleComposition.java.txt, services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/ForecastList.java.txt, services/bonita-business-data/bonita-business-data-impl/src/test/resources/org/bonitasoft/engine/bdm/client/Skill.java.txt
The generated method 'hashcode' declares a local variable suffixed by  'Code', this local variable will hide the global variable named '*Code' causing the compilation error.
To solve the issue, all global variables were prefixed b y 'this.'
The same fix was done for 'equals' method.
=> BS-14371, avoid variable names conflicts

services/bonita-classloader/bonita-classloader-impl/src/main/java/org/bonitasoft/engine/classloader/VirtualClassLoader.java, services/bonita-classloader/bonita-classloader-impl/src/test/java/org/bonitasoft/engine/classloader/VirtualClassLoaderTest.java, services/bonita-commons/src/main/java/org/bonitasoft/engine/data/instance/model/impl/XStreamFactory.java
Cause: XStreamFactory keeps a map ClassLoader -> XStream instance: when VirtualClassLoader.destroy()  is called the referenced BonitaClassLoader is destroyed,
but the VirtualClassLoader itself is remains and will be used to reference a new BonitaClassLoader. In this way, the map of XStreamFactory keep the entry containing
a XStream instance pointing to the destroyed BonitaClassLoader.
Fix: remove the entry related to the VirtualClassLoader being destroyed when VirtualClassLoader.destroy() is called.
=> BS-14495, discard XStream instance when the classLoader is destroyed

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/process/GatewayExecutionIT.java, bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/search/SearchActivityInstanceIT.java, services/bonita-persistence/bonita-persistence-db/src/main/java/org/bonitasoft/engine/persistence/AbstractDBPersistenceService.java, services/bonita-persistence/bonita-persistence-db/src/test/java/org/bonitasoft/engine/persistence/AbstractDBPersistenceServiceTest.java, services/bonita-persistence/bonita-persistence-hibernate/src/main/java/org/bonitasoft/engine/persistence/AbstractHibernatePersistenceService.java, services/bonita-persistence/bonita-persistence-hibernate/src/test/java/org/bonitasoft/engine/persistence/AbstractHibernatePersistenceServiceTest.java
escape quotes in search in order to prevent injection + work with name having quotes
wanted to replace hql query generation by generating hibernate parameters but it was breaking the filters with e.g. long that were given as string
so only replaced quotes in the search term
=> BS-14485, escape string in search

bpm/bonita-connector-service/bonita-connector-service-api-impl/src/main/java/org/bonitasoft/engine/core/connector/impl/ConnectorServiceImpl.java, services/bonita-connector-executor/bonita-connector-executor-api-impl/src/main/java/org/bonitasoft/engine/connector/impl/ConnectorExecutorImpl.java, services/bonita-expression/bonita-expression-api-impl/src/main/java/org/bonitasoft/engine/expression/impl/GroovyScriptExpressionExecutorCacheStrategy.java, services/bonita-expression/bonita-expression-api-impl/src/test/java/org/bonitasoft/engine/expression/impl/GroovyScriptExpressionExecutorCacheStrategyTest.java
If a script was throwing a throwable it was not catch by the expression executor resulting in unexpected behavior on the rest of the engine
Fixed it by catching throwable in the groovy script executor
=> BS-14258, catch throwable on groovy scripts

bonita-integration-tests/bonita-integration-tests-local/src/main/resources/logback-test.xml
reactivate FailureHandlingWork logging because it was hidding failing work in test logs
=> ctivate error log for test in case of failure

bonita-integration-tests/bonita-integration-tests-local/src/test/java/org/bonitasoft/engine/cache/CacheServiceTest.java, bpm/bonita-home/src/main/resources/bonita-platform-community.xml, bpm/bonita-home/src/main/resources/bonita-tenant-community.xml, services/bonita-cache/bonita-cache-ehcache/src/main/java/org/bonitasoft/engine/cache/ehcache/CommonEhCacheCacheService.java, services/bonita-cache/bonita-cache-ehcache/src/main/java/org/bonitasoft/engine/cache/ehcache/EhCacheCacheService.java, services/bonita-cache/bonita-cache-ehcache/src/main/java/org/bonitasoft/engine/cache/ehcache/PlatformEhCacheCacheService.java, services/bonita-cache/bonita-cache-ehcache/src/test/java/org/bonitasoft/engine/cache/ehcache/CommonEhCacheCacheServiceTest.java, services/bonita-expression/bonita-expression-api-impl/src/test/java/org/bonitasoft/engine/expression/impl/GroovyScriptExpressionExecutorCacheStrategyTest.java
Instead of retrieve the tenant id from the SessionAccessor, use directly the value injected by Spring in the bonita.home. This avoid exceptions in the case of the tenant id is not set in the session accessor.
=> Inject the tenantId directly from Spring bean

services/bonita-classloader/bonita-classloader-api/src/main/java/org/bonitasoft/engine/classloader/ClassLoaderService.java, services/bonita-classloader/bonita-classloader-impl/src/main/java/org/bonitasoft/engine/classloader/ClassLoaderServiceImpl.java, services/bonita-classloader/bonita-classloader-impl/src/main/java/org/bonitasoft/engine/classloader/listeners/ClassReflectorClearer.java, services/bonita-classloader/bonita-classloader-impl/src/test/java/org/bonitasoft/engine/classloader/ClassLoaderServiceImplTest.java, services/bonita-classloader/bonita-classloader-impl/src/test/java/org/bonitasoft/engine/classloader/listeners/ClassReflectorClearerTest.java, services/bonita-commons/src/main/java/org/bonitasoft/engine/commons/ClassReflector.java
add global listener in the classloader service add use it to clear cache
of classreflector
the listener is directly added in the classloader service because it was
the easier given that class reflector is inside the bonita-commons
module
=> add global listeners + listener on classreflector

services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/bdm/EqualsBuilderTest.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/bdm/HashCodeBuilderTest.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/bdm/server/ServerBDMJarBuilderTest.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/compiler/JDTCompilerTest.java, services/bonita-commons/src/main/java/org/bonitasoft/engine/commons/io/IOUtil.java
this methods purpose was to create temporary folders
it was dangerous because it was registering a new shutdown hook for each
folder created
a shutdown hook is expensive in terms of memory because it create a
thread each time
use junit rule instead
=> remove dangerous method in IOUtils

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/business/data/BDRepositoryIT.java, bpm/bonita-core/bonita-operation/bonita-operation-api-impl/src/main/java/org/bonitasoft/engine/core/operation/impl/XpathUpdateQueryOperationExecutorStrategy.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/classloader/BonitaBPMParentClassLoaderResolverTest.java, bpm/bonita-home/src/main/resources/bonita-tenant-community.xml, services/bonita-business-data/bonita-business-data-impl/pom.xml, services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/JPABusinessDataRepositoryImpl.java, services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/JsonBusinessDataSerializerImpl.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/ConcurrencyIT.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/JPABusinessDataRepositoryImplITest.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/JPABusinessDataRepositoryImplTest.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/JsonBusinessDataSerializerImplTest.java
BusinessDataService use listeners to listen updates on the classloaders
and refresh itself by clearing cache in JSon and recreating the entity
manager factory. this remove all reference on the destroyed bonita
classloader
depends on https://github.com/bonitasoft/bonita-engine/pull/220
=> Use global listeners to clear reference to classes

pom.xml
the version 2.4.4 is the same as the version used by restlet in the web
this is needed in order to call the clearCache on TypeFactory
depends on https://github.com/bonitasoft/bonita-engine/pull/220 and https://github.com/bonitasoft/bonita-engine/pull/221
=> update jackson version to 2.4.4

services/bonita-transaction/bonita-transaction-impl/src/main/java/org/bonitasoft/engine/transaction/JTATransactionServiceImpl.java, services/bonita-transaction/bonita-transaction-impl/src/test/java/org/bonitasoft/engine/transaction/JTATransactionServiceImplTest.java
The bug was fixed in 6.5.3 where resetTxCounter was called
Before that reset tx counter was called only in the synchronization (the remove) so if the tx was killed by the txManager the status was not cleaned up
=> BS-13411, add test on nested transaction finally

services/bonita-classloader/bonita-classloader-impl/src/main/java/org/bonitasoft/engine/classloader/VirtualClassLoader.java
This is top avoid classloader read and update the same list at the same
time, we make a copy of the list when doing the notify
=> make classloader listeners synchronized

bpm/bonita-home/src/main/resources/bonita-platform-community.xml
Merging PR https://github.com/bonitasoft/bonita-distrib/pull/22 made quartz locked while shutting down when used with H2 database on CI.
Using this quartz plugin to shutdown quartz scheduler when JVM is terminating.
=> Fix quartz shutdown with shutdown hook plugin

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/process/document/DocumentIT.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/core/document/api/impl/DocumentHelper.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/core/document/api/impl/DocumentHelperTest.java
the document list operation was accepting only FileInput from contract
and the object document value.
It is now accepting Document that are existing documents, in this case
it retrieves the content + filename + mimetype or the url
=> fix set document list with an other list

bpm/bonita-sql/src/main/resources/sql/h2/createTables.sql, bpm/bonita-sql/src/main/resources/sql/mysql/createTables.sql, bpm/bonita-sql/src/main/resources/sql/oracle/createTables.sql, bpm/bonita-sql/src/main/resources/sql/postgres/createTables.sql, bpm/bonita-sql/src/main/resources/sql/sqlserver/createTables.sql
this fix the mysql slowness on search archive case involving user, on
big volume it goes from 45 minutes to 15 seconds for the count and 30ms
for the query
mainly it comes from the index order
in additions we should implement a count that only says that there is
more than e.g. 1000 element, with this the diplay will go on mysql from
15 seconds to arround 100ms
this issue was only on mysal but we keep the same index for other db
also. tested it on postgres, it is ok
=> BS-14736, change index on arch flow node instance

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/form/FormMappingIT.java, bpm/bonita-core/bonita-form-mapping/bonita-form-mapping-impl/src/main/java/org/bonitasoft/engine/core/form/impl/FormMappingServiceImpl.java, bpm/bonita-core/bonita-form-mapping/bonita-form-mapping-impl/src/test/java/org/bonitasoft/engine/core/form/impl/FormMappingServiceImplTest.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/resolver/DocumentInitialValueArtifactManagerTest.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/api/impl/resolver/FormMappingAndPageArtifactManagerTest.java
this is to avoid not found when a form mapping is to none and you call
the resolvePageOrUrl method
the method now returns a pagemapping object with no pageid nor url
this still can be updated to other values
=> BS-14661, make NONE formmapping create pagemapping

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/business/data/BDRepositoryIT.java, bpm/bonita-core/bonita-operation/bonita-operation-api-impl/src/main/java/org/bonitasoft/engine/core/operation/impl/XpathUpdateQueryOperationExecutorStrategy.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/command/ExecuteBDMQueryCommand.java, bpm/bonita-home/src/main/resources/bonita-tenant-community.xml, pom.xml, services/bonita-business-data/bonita-business-data-api/src/main/java/org/bonitasoft/engine/business/data/proxy/ServerProxyfier.java, services/bonita-business-data/bonita-business-data-client-resources/src/main/java/org/bonitasoft/engine/bdm/dao/client/resources/proxy/Proxyfier.java, services/bonita-business-data/bonita-business-data-impl/pom.xml, services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/BusinessDataServiceImpl.java, services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/JPABusinessDataRepositoryImpl.java, services/bonita-business-data/bonita-business-data-impl/src/main/java/org/bonitasoft/engine/business/data/impl/JsonBusinessDataSerializerImpl.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/ConcurrencyIT.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/JPABusinessDataRepositoryImplITest.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/JPABusinessDataRepositoryImplTest.java, services/bonita-business-data/bonita-business-data-impl/src/test/java/org/bonitasoft/engine/business/data/impl/JsonBusinessDataSerializerImplTest.java
In order to be able to retrieve from error generated from the BDR
reloading (concurency) persistence exception thrown by the entity
manager are now converted to retryable exception, this way the
transaction manager is able to retry the transaction
=> Make persistence except from the BDR be retryable

bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/DocumentAPIImpl.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/bpm/contract/validation/ContractStructureValidator.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/contract/validation/ContractStructureValidatorTest.java, bpm/bonita-core/bonita-process-engine/src/test/java/org/bonitasoft/engine/bpm/contract/validation/builder/MapBuilder.java
Eg. in the case of given inputs:
{"facture":{"lignes":[null]}}
the validation succeeds and the NULL is just ignored.
We validated with Nicolas the funtional behaviour.
=> BS-14869 Support of null values in contract input validation for lists

bonita-integration-tests/bonita-integration-tests-client/src/main/java/org/bonitasoft/engine/activity/ContractIT.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/ProcessAPIImpl.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/api/impl/ProcessStarter.java, bpm/bonita-core/bonita-process-engine/src/main/java/org/bonitasoft/engine/command/AbstractStartProcessCommand.java, bpm/bonita-core/bonita-process-instance/bonita-process-instance-api/src/main/java/org/bonitasoft/engine/core/process/instance/api/exceptions/SContractViolationException.java
startProcessWithInputs now throw SContractViolationException, before it
was throwing Retrieve Exception because of a wrong catch and convertion
of server/client exceptions
=> BS-14697, fix start process exceptions on contract
